[package]
name = "font"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/font"
homepage = "https://github.com/hilbert-space/font"
description = "Font."
